### ISSUE TITLE
Cannot compile with current instructions

### ISSUE THREAD

**Issue by thegreyshadow** [bryanherger/xdrawchem#2]
Hi Bryan! You might remember me from the old days. I contributed some Mandrake rpm packages. Now I use Slackware. I would like to package xdrawchem 1.10 but I cannot compile it.

The biggest trouble spot here is that the INSTALL.txt instructions which are in the source tarball are not helpful. (For example, they tell me to run first "./configure", but there's no configure script at all.

Just typing 'make' also fails.

I'd aprreciate any hint or workaround.

Thanks,

Eduardo

**Comment by bryanherger** [comment]
Hi!  Sorry I've been away for a while.  It looks like I forgot to update all of the documents and instructions with the new build process.  Here's a summary:

To install XDrawChem:

1) Install recent Qt and OpenBabel from packages or source.
If installing from packages, please also install the "devel" packages as well, e.g. qt5-qtbase-devel and openbabel-devel.
XDrawChem is built with Qt 5.6 and OpenBabel 2.2.3
Please file an issue on GitHub if these versions or newer fail.

2) Type "qmake".
   This will generate the XDrawChem Makefiles.

   Then type "make", followed by (as root) "make install" to build and install.

I suppose this issue is a broader documentation issue, which I will have to fix soon.  Thanks!

**Comment by thegreyshadow** [comment]
Hi bryan! Thank you! Now I can have a good makefile. Don't close the issue yet, I still cannot build the software. I ask you to keep this open in case the build failure has something to do with this. I will open another issue to report the error. Thanks again!

**Comment by thegreyshadow** [comment]
Closing the issue. INSTALL.txt in 1.10.1 gives correct instructions. Thanks Bryan!
